FreshMarketMVC/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        // insert and update
        public IActionResult Upsert(int? id)
        {
            Brand brand = new Brand();
            if(id == null)
            {
                // this is for create
                return View(brand);
            }

            //this is for edit
            brand = _unitOfWork.Brand.Get(id.GetValueOrDefault());
            if(brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // insert and update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if(brand.Id == 0)
                {
                    _unitOfWork.Brand.Add(brand); // insert
                }
                else
                {
                    _unitOfWork.Brand.Update(brand); // update
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        #region API CALLS

        // api get
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Brand.GetAll();
            return Json(new { data = allObj });
        }

        // api delete
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Brand.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }
            _unitOfWork.Brand.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

FreshMarketMVC/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using OrganicFoodMVC.Utility;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using HtmlAgilityPack;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        // info path to save image
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;

        }

        public IActionResult Index()
        {
            return View();
        }

        // insert and update product
        public IActionResult Upsert(int? id)
        {
            IEnumerable<Category> CatList = _unitOfWork.Category.GetAll();
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),
                CategoryList = CatList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                BrandList = _unitOfWork.Brand.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                UnitList = _unitOfWork.Unit.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            if (id == null)
            {
                //this is for create
                return View(productVM);
            }
            //this is for edit
            productVM.Product = _unitOfWork.Product.Get(id.GetValueOrDefault());
            if (productVM.Product == null)
            {
                return NotFound();
            }
            return View(productVM);

        }

        // info path to save image
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM)
        {

            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images\products");
                    var extenstion = Path.GetExtension(files[0].FileName);

                    if (productVM.Product.ImageUrl != null)
                    {
                        //this is an edit and we need to remove old image

                        var imagePath = Path.Combine(webRootPath, productVM.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                    {
                        files[0].CopyTo(filesStreams);
                    }
                    productVM.Product.ImageUrl = @"\images\products\" + fileName + extenstion;
                }
                else
                {
                    //update when they do not change the image
                    if (productVM.Product.Id != 0)
                    {
                        Product objFromDb = _unitOfWork.Product.Get(productVM.Product.Id);
                        productVM.Product.ImageUrl = objFromDb.ImageUrl;
                    }
                }

                // insert
                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);

                }
                else // update
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else // assign cateList and BrandList if modelState.IsVaild false
            {
                IEnumerable<Category> CatList = _unitOfWork.Category.GetAll();
                productVM.CategoryList = CatList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                productVM.BrandList = _unitOfWork.Brand.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                productVM.UnitList = _unitOfWork.Unit.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                if (productVM.Product.Id != 0)
                {
                    productVM.Product = _unitOfWork.Product.Get(productVM.Product.Id);
                }
            }
            return View(productVM);
        }

        public ActionResult ExportToExcel()
        {
            var doctors = _unitOfWork.Product.GetAll(includeProperties: "Category,Brand,Unit");

            byte[] fileContents;
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("DoctorsInfo");
            Sheet.Cells["B1"].Value = "Mã Sản Phẩm";
            Sheet.Cells["C1"].Value = "Tên Sản Phẩm";
            //Sheet.Cells["C1"].Value = "Mô tả ";
            Sheet.Cells["D1"].Value = "Số lượng";
            Sheet.Cells["E1"].Value = "Giá";
            Sheet.Cells["F1"].Value = "Link ảnh";
            Sheet.Cells["G1"].Value = "Loại sản phẩm";
            Sheet.Cells["H1"].Value = "Thương hiệu";
            Sheet.Cells["I1"].Value = "Đơn vị";


            int row = 2;
            foreach (var item in doctors)
            {
                //var doc = new HtmlDocument();
                //doc.LoadHtml(item.Discription);
                //var innertext = doc.DocumentNode.InnerText; 
                Sheet.Cells[string.Format("B{0}", row)].Value = item.Id;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.Name;
                //Sheet.Cells[string.Format("C{0}", row)].Value = innertext;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.Quantity;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.Price;
                Sheet.Cells[string.Format("F{0}", row)].Value = item.ImageUrl;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.Category.Name;
                Sheet.Cells[string.Format("H{0}", row)].Value = item.Brand.Name;
                Sheet.Cells[string.Format("I{0}", row)].Value = item.Unit.Name;

                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            fileContents = Ep.GetAsByteArray();

            if (fileContents == null || fileContents.Length == 0)
            {
                return NotFound();
            }

            return File(
                fileContents: fileContents,
                contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileDownloadName: "SanPhamcuaOrganicFood.xlsx"
            );
        }

        private ActionResult NotFound()
        {
            throw new NotImplementedException();
        }


        #region API CALLS

        // API get product
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Product.GetAll(includeProperties: "Category,Brand,Unit");
            return Json(new { data = allObj });
        }

        // API delete product
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Product.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }

            // delete image
            string webRootPath = _hostEnvironment.WebRootPath;
            var imagePath = Path.Combine(webRootPath, objFromDb.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _unitOfWork.Product.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

FreshMarketMVC/Areas/Admin/Controllers/UnitController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UnitController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UnitController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        // show insert and update
        public IActionResult Upsert(int? id)
        {
            Unit unit = new Unit();
            if (id == null)
            {
                // this is for create
                return View(unit);
            }

            //this is for edit
            unit = _unitOfWork.Unit.Get(id.GetValueOrDefault());
            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        // insert and update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Unit unit)
        {
            if (ModelState.IsValid)
            {
                if (unit.Id == 0)
                {
                    _unitOfWork.Unit.Add(unit); // insert
                }
                else
                {
                    _unitOfWork.Unit.Update(unit); // update
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        #region API CALLS

        // api get unit
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Unit.GetAll();
            return Json(new { data = allObj });
        }

        //api delete unit
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Unit.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }
            _unitOfWork.Unit.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

FreshMarketMVC/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrganicFoodMVC.DataAccess.Data;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        

        #region API CALLS

        // api get user
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.Include(u=>u.Company).ToList();

            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            
            foreach(var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if(user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }    
            }    

            return Json(new { data = userList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Lỗi không thể khóa!" });
            }
            if(objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                // user is currently locked, will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Thành công!" });
        }

        #endregion
    }
}

FreshMarketMVC/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Tạo Mới</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Trở Về</a>
    </div>
</div>

FreshMarketMVC/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Cập Nhập</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Trờ Về</a>
    </div>
</div>

FreshMarketMVC/Views/Shared/_Layout.cshtml
@using OrganicFoodMVC.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - TA Shop</title>                                                                              

    <link rel="icon" href="/images/icon/logo.png" type="image/x-icon">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Assets/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/Assets/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Assets/css/toastr.min.css" />
    <script src="~/Assets/js/jquery.min.js"></script>

    <!-- Bootstrap4 files-->
    <link href="~/Assets/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Assets/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Assets/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Assets/css/responsive.css" rel="stylesheet" type="text/css" />

</head>
<body>

    <header class="section-header mb-5">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-8">
                        <a href="">
                            <img width="250" src="~/assets/images/logoTAShop_1.png" />
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">

                        @if (!User.IsInRole(SD.Role_Admin) && !User.IsInRole(SD.Role_Employee))
                        {
                            @await Component.InvokeAsync("Search")
                        }

                    </div> <!-- col.// -->
                    <div class="col-xl-3 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">

                            <partial name="_LoginPartial" />

                            @if (User.IsInRole(SD.Role_Employee))
                            {
                                <div class="widget-header mr-3">
                                    <a asp-area="Admin" asp-controller="Order" asp-action="index" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-store"></i>
                                        </div>
                                        <small class="text"> Hóa đơn </small>
                                    </a>
                                </div>
                            } else if (User.IsInRole(SD.Role_User_Indi)) 
                            { 
                                <div class="widget-header mr-3">
                                    <a asp-area="Customer" asp-controller="Order" asp-action="index" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-store"></i>
                                        </div>
                                        <small class="text"> Hóa đơn </small>
                                    </a>
                                </div>
                            }
                            @if (User.IsInRole(SD.Role_User_Indi))
                            {
                                @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart) != null)
                                {
                                    <div class="widget-header">
                                        <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="widget-view">
                                            @{
                                                var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart);
                                            }
                                            <div class="icon-area">
                                                <i class="fa fa-shopping-cart"></i>
                                                <span class="notify">@count</span>
                                            </div>
                                            <small class="text"> Giỏ hàng </small>
                                        </a>
                                    </div>
                                }
                                else
                                {
                                    <div class="widget-header">
                                        <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="widget-view">
                                            <div class="icon-area">
                                                <i class="fa fa-shopping-cart"></i>
                                                <span class="notify">0</span>
                                            </div>
                                            <small class="text"> Giỏ hàng </small>
                                        </a>
                                    </div>
                                }
                            }
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                         @if (!User.IsInRole(SD.Role_Admin) && !User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                            </li>
                        
                            @await Component.InvokeAsync("MenuCategory")
                        }
                        
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Danh mục quản lý
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Danh mục sản phẩm</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Thương hiệu</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Sản phẩm</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Unit" asp-action="Index">Đơn vị tính</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Tài khoản người dùng</a>
                                </div>
                            </li>
                        }
                        @if (!User.IsInRole(SD.Role_Admin) && !User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Thông tin liên hệ</a>
                            </li>
                        }
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary mt-5">
        <div class="container">
            <section class="footer-bottom text-center">
                <p class="text-white">Thực phẩm sạch - Tươi ngon</p>
                <p class="text-muted"> &copy 2022 Fresh Market</p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <!-- jQuery -->
    <script src="~/Assets/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Assets/js/bootstrap.bundle.min.js" type="text/javascript"></script>

    <!-- custom javascript -->
    <script src="~/Assets/js/script.js" type="text/javascript"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Assets/js/jquery-ui.min.js"></script>
    <script src="~/Assets/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/toastr.min.js"></script>
    <script src="~/Assets/js/sweetalert.min.js"></script>
    <script src="~/Assets/js/e19c476714.js"></script>
    <script src="~/Assets/js/ellipsis.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>